[snowflake]
account = "GADPUES-WI18599"
user = "PRANAVI09"
api_key = "eyJraWQiOiIyMzM3MjkzNTE3MyIsImFsZyI6IkVTMjU2In0.eyJwIjoiOTEzMDAzNTY6OTEzMDA0ODQiLCJpc3MiOiJTRjozMDAxIiwiZXhwIjoxODIyNjMyOTcwfQ.rCNurPmidtLgAI1VKBkfYqPOYYygpLNMuupyo51RUHjcQUHs_7HcBarohIovqQE00gZkt6OsOg_GosonvZr_HQ"
role = "ACCOUNTADMIN"
host = "GADPUES-WI18599.snowflakecomputing.com"

[mealdb]
api_key = "1"
